todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls')),
]

todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('login', views.LoginFormView.as_view(), name='login'),
    path('logout', views.LogoutFormView.as_view(), name='logout'),
    path('create', views.createView, name='create'),
    path('delete/<int:task_id>', views.deleteView, name='delete'),
    path('update/<int:task_id>', views.updateView, name='update'),
]

todos/models.py
from django.db import models


class Task(models.Model):
	user = models.CharField(max_length=200)
	description = models.CharField(max_length=200)

todos/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Task

class LoginFormView(LoginView):
	template_name = 'todos/login.html'
	next_page = reverse_lazy('todos:index')

class LogoutFormView(LogoutView):
	next_page = reverse_lazy('todos:login')

@login_required(login_url=reverse_lazy('todos:login'))
def indexView(request):
	obj = Task.objects.filter(user=request.user)

	return render(request, "todos/index.html", {"todo_list": obj})

@login_required(login_url=reverse_lazy('todos:login'))
def createView(request):
	if request.method == 'POST':
		new_task = request.POST['tname']

		if new_task:
			obj = Task(description=new_task, user=request.user)
			obj.save()

	return HttpResponseRedirect(reverse('todos:index'))

@login_required(login_url=reverse_lazy('todos:login'))
def deleteView(request, task_id):
	obj = Task.objects.get(id=task_id)
	obj.delete()

	return HttpResponseRedirect(reverse('todos:index'))

@login_required(login_url=reverse_lazy('todos:login'))
def updateView(request, task_id):
	if request.method == 'POST':
		obj = Task.objects.get(id=task_id)
		new_desc = request.POST['newtask']

		if len(new_desc) > 0:
			obj.description = new_desc
			obj.save()

			return HttpResponseRedirect(reverse('todos:index'))

	obj = Task.objects.filter(user=request.user)
	edit_obj = Task.objects.get(id=task_id)
	return render(request, "todos/todos_update.html", {"todo_list": obj, "todo_edit": edit_obj})

todos/templates/todos/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	<title>TODO</title>

</head>
<body>
	{% block login-content %}

	<table>
		<tr>
			<th></th>
			<th></th>
		</tr>
		<tr>
			<td>{{ request.user }}</td>
			<td><a href="{% url 'todos:logout' %}">Logout</a></td>
		</tr>

	</table>

	{% endblock %}
	<hr>

	<h1>Welcome to TODO List</h1>

	<form action="{% url 'todos:create' %}" method="POST">
		{% csrf_token %}
		<div class="input-group">
			{% if todo_edit %}
			<input type="text" class="form-control" placeholder="What's your TODO?" aria-label="Insert new task field with two button addons" name="tname">
			{% else %}
			<input type="text" class="form-control" placeholder="What's your TODO?" aria-label="Insert new task field with two button addons" name="tname" autofocus>
			{% endif %}
			<button class="btn btn-outline-secondary">Save</button>
		</div>
	</form>

	{% block content %}
	
	{% if todo_list %}
	<table class="table table-sm">
		<tr>
			<th>Task</th>
			<th></th>
			<th></th>
		</tr>
		{% for task in todo_list %}
		<tr>
			<td>{{ task.description }}</td>
			<td>
				<a href="{% url 'todos:update' task.id %}" class="btn btn-primary" tabindex="-1" role="button">Update</a>
				<a href="{% url 'todos:delete' task.id %}" class="btn btn-danger" tabindex="-1" role="button">Done</a>
			</td>
		</tr>
		{% endfor %}
	</table>
	{% else %}
	<p>Hey you can insert some text up there!</p>
	{% endif %}

	{% endblock %}

</body>
</html>

todos/templates/todos/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Login</title>
</head>
<body>

    <form method="POST">
        <div class="imgcontainer">
            <img src="{% static 'src/project_logo.png' %}" alt="ziqzed login logo">
        </div>

        <div class="container">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="inputcontainer">
                <input type="submit" value="Login">
            </div>

            <p>No account yet? <a href=".">Register here</a></p>
        </div>
    </form>

</body>
</html>

todos/templates/todos/todos_update.html
{% extends "todos/index.html" %}

{% block content %}

{% if todo_list %}
<form action="{% url 'todos:update' todo_edit.id %}" method="POST">
	{% csrf_token %}
	<table class="table table-sm">
		<tr>
			<th>Task</th>
			<th></th>
			<th></th>
		</tr>
		{% for task in todo_list %}
		<tr>
			{% if task.id == todo_edit.id %}
			<td><input type="text" class="form-control" name="newtask" value="{{ task.description }}" autofocus></td>
			<td>
				<button class="btn btn-primary" tabindex="-1" type="submit">Confirm</button>
				<button class="btn btn-danger" tabindex="-1" role="button" type="reset">Cancel</button>
			</td>
			{% else %}
			<td>{{ task.description }}</td>
			<td></td>
			{% endif %}
		</tr>
		{% endfor %}
	</table>
	{% else %}
	<p>Hey you can insert some text up there!</p>
	{% endif %}
</form>
	

{% endblock %}